package com.javaclimb.xshopping.entity;

import javax.persistence.*;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table seckill_info
 */
@Table(name = "seckill_info")
public class SeckillInfo {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_info.id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_info.starttime
     *
     * @mbg.generated
     */
    @Column(name = "starttime")
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_info.overtime
     *
     * @mbg.generated
     */
    @Column(name = "overtime")
    private Date overtime;

    /**
     * Database Column Remarks:
     *   所属商品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_info.goodsId
     *
     * @mbg.generated
     */
    @Column(name = "goodsid")
    private Long goodsid;



    @Transient
    private String name;

    /**
     * Database Column Remarks:
     *   商品价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.price
     *
     * @mbg.generated
     */
    @Transient
    private Double price;

    /**
     * Database Column Remarks:
     *   商品折扣价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.discount
     *
     * @mbg.generated
     */
    @Transient
    private Double discount;

    /**
     * Database Column Remarks:
     *   商品销量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.sales
     *
     * @mbg.generated
     */
    @Transient
    private Integer sales;

    /**
     * Database Column Remarks:
     *   商品点赞数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.hot
     *
     * @mbg.generated
     */
    @Transient
    private Integer hot;

    /**
     * Database Column Remarks:
     *   是不是推荐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.recommend
     *
     * @mbg.generated
     */
    @Transient
    private String recommend;

    /**
     * Database Column Remarks:
     *   库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.count
     *
     * @mbg.generated
     */
    @Transient
    private Integer count;

    /**
     * Database Column Remarks:
     *   所属类别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.typeId
     *
     * @mbg.generated
     */
    @Transient
    private Long typeid;

    /**
     * Database Column Remarks:
     *   商品图片ID，用英文, 隔开
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.fields
     *
     * @mbg.generated
     */
    @Transient
    private String fields;

    /**
     * Database Column Remarks:
     *   所属卖家
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.userId
     *
     * @mbg.generated
     */
    @Transient
    private Long userid;

    /**
     * Database Column Remarks:
     *   所属卖家等级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.level
     *
     * @mbg.generated
     */
    @Transient
    private Integer level;

    /**
     * Database Column Remarks:
     *   商品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.description
     *
     * @mbg.generated
     */
    @Transient
    private String description;




    @Transient
    private String statime;

    @Transient
    private String ovetime;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_info.id
     *
     * @return the value of seckill_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_info.id
     *
     * @param id the value for seckill_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_info.starttime
     *
     * @return the value of seckill_info.starttime
     *
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_info.starttime
     *
     * @param starttime the value for seckill_info.starttime
     *
     * @mbg.generated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_info.overtime
     *
     * @return the value of seckill_info.overtime
     *
     * @mbg.generated
     */
    public Date getOvertime() {
        return overtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_info.overtime
     *
     * @param overtime the value for seckill_info.overtime
     *
     * @mbg.generated
     */
    public void setOvertime(Date overtime) {
        this.overtime = overtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_info.goodsId
     *
     * @return the value of seckill_info.goodsId
     *
     * @mbg.generated
     */
    public Long getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_info.goodsId
     *
     * @param goodsid the value for seckill_info.goodsId
     *
     * @mbg.generated
     */
    public void setGoodsid(Long goodsid) {
        this.goodsid = goodsid;
    }

    public String getStatime() {
        return statime;
    }

    public void setStatime(String statime) {
        this.statime = statime;
    }

    public String getOvetime() {
        return ovetime;
    }

    public void setOvetime(String ovetime) {
        this.ovetime = ovetime;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Double getDiscount() {
        return discount;
    }

    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    public Integer getSales() {
        return sales;
    }

    public void setSales(Integer sales) {
        this.sales = sales;
    }

    public Integer getHot() {
        return hot;
    }

    public void setHot(Integer hot) {
        this.hot = hot;
    }

    public String getRecommend() {
        return recommend;
    }

    public void setRecommend(String recommend) {
        this.recommend = recommend;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Long getTypeid() {
        return typeid;
    }

    public void setTypeid(Long typeid) {
        this.typeid = typeid;
    }

    public String getFields() {
        return fields;
    }

    public void setFields(String fields) {
        this.fields = fields;
    }

    public Long getUserid() {
        return userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}